#!/bin/sh

cd $(dirname $0)

{
  python3 main.py
} || {
  {
    python3 -m pip install -i https://pypi.tuna.tsinghua.edu.cn/simple pygame
  } || {
    echo 运行错误！请检查你是否安装 Python 3。
    echo 若未安装，请在此下载并安装 Python 3: https://www.python.org/downloads/release/python-3108
    echo 请不要安装 Python 3.11，因为 Pygame 不兼容这个版本。
    read -p "按 Enter 退出。"
    exit
  }
  python3 -m pip install -i https://pypi.tuna.tsinghua.edu.cn/simple numpy
  python3 -m pip install -i https://pypi.tuna.tsinghua.edu.cn/simple numba
  python3 main.py
}
